AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dream-bot
  Sample SAM Template for dream-bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  DreamBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: dream-bot
      CodeUri: dream_bot/
      Handler: app.lambda_handler
      Runtime: python3.10
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: dreams
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # Can convert to HttpApi later
          Properties:
            Path: /
            Method: post

      Environment:
        Variables:
          # AWS Parameter Store Paths
          TELEGRAM_BOT_TOKEN: !Sub '{{resolve:ssm:/dream-bot/bot-api-token}}'
          DREAM_CHANNEL_ID: !Sub '{{resolve:ssm:/dream-bot/dream-channel-id}}'

  EventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: dream-bot
      MaximumRetryAttempts: 0
      Qualifier: $LATEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DreamBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  DreamBotFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DreamBotFunction.Arn
  DreamBotFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DreamBotFunctionRole.Arn
